
    ##note if you are deploying via docker or kubernetes, this url as in defaultZone will change
spring:
  application:
    name: department-service

  config:
    import: "optional:configserver:http://localhost:8088"

