
server:
  port: 8060

eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/employee/**
        - id: department-service
          url: lb://department-service
          predicates:
              - Path=/department/**

management:
  tracing:
    sampling:
      probability: 1.0